
name: InstanceForExtensble
dependencies:
- base
- text
- bytestring
- constraints
- containers
- unordered-containers
- mtl
- extensible
- cassava
- data-default-class
- sqlite-simple
- hspec

library:
  source-dirs: src

executables:
  InstanceForExtensble-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:  
    - InstanceForExtensble

tests:
  InstanceForExtensble-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - InstanceForExtensble

